/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.editor.idea.lang


class ArchitectureLangFileType extends AbstractArchitectureLangFileType {
	public static final ArchitectureLangFileType INSTANCE = new ArchitectureLangFileType()
	
	new() {
		super(ArchitectureLangLanguage.INSTANCE)
	}
}
