/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.ide


/**
 * Use this class to register ide components.
 */
class ArchitectureLangIdeModule extends AbstractArchitectureLangIdeModule {
}
