/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.architectureLang.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>ArchitectureLang</b></em>' model.
 * <!-- end-user-doc -->
 * @generated
 */
public class ArchitectureLangAllTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new ArchitectureLangAllTests("ArchitectureLang Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ArchitectureLangAllTests(String name) {
		super(name);
	}

} //ArchitectureLangAllTests
