/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.architectureLang.tests;

import com.laegler.microservice.modeler.architectureLang.ArchitectureLangFactory;
import com.laegler.microservice.modeler.architectureLang.Expose;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Expose</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ExposeTest extends TestCase {

	/**
	 * The fixture for this Expose test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Expose fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ExposeTest.class);
	}

	/**
	 * Constructs a new Expose test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ExposeTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Expose test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(Expose fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Expose test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Expose getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ArchitectureLangFactory.eINSTANCE.createExpose());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ExposeTest
