/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.architectureLang.tests;

import com.laegler.microservice.modeler.architectureLang.ArchitectureLangFactory;
import com.laegler.microservice.modeler.architectureLang.Jar;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Jar</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class JarTest extends ArtifactTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(JarTest.class);
	}

	/**
	 * Constructs a new Jar test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JarTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Jar test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Jar getFixture() {
		return (Jar)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ArchitectureLangFactory.eINSTANCE.createJar());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //JarTest
