/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.architectureLang.tests;

import com.laegler.microservice.modeler.architectureLang.ArchitectureLangFactory;
import com.laegler.microservice.modeler.architectureLang.RestExpose;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Rest Expose</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RestExposeTest extends ExposeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RestExposeTest.class);
	}

	/**
	 * Constructs a new Rest Expose test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RestExposeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Rest Expose test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected RestExpose getFixture() {
		return (RestExpose)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ArchitectureLangFactory.eINSTANCE.createRestExpose());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RestExposeTest
