/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.architectureLang.tests;

import com.laegler.microservice.modeler.architectureLang.ArchitectureLangFactory;
import com.laegler.microservice.modeler.architectureLang.Spring;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Spring</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SpringTest extends ArtifactTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SpringTest.class);
	}

	/**
	 * Constructs a new Spring test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpringTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Spring test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Spring getFixture() {
		return (Spring)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(ArchitectureLangFactory.eINSTANCE.createSpring());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SpringTest
