/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.yaml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ArchitectureYamlRuntimeModule extends AbstractArchitectureYamlRuntimeModule {
}
