/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArchitectureLangStandaloneSetup extends ArchitectureLangStandaloneSetupGenerated {

	def static void doSetup() {
		new ArchitectureLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
