/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ArchitectureLangRuntimeModule extends AbstractArchitectureLangRuntimeModule {
}
