apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: code2model-001
  labels:
    app: mysql
    provider: john.doe
    group: org.example
    project: mysql
    version: 0.0.1-SNAPSHOT
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volume-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 30