/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.idea.completion

import com.laegler.microservice.modeler.idea.lang.ArchitectureLangLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class ArchitectureLangCompletionContributor extends AbstractArchitectureLangCompletionContributor {
	new() {
		this(ArchitectureLangLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
