/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.yaml.idea.lang


class ArchitectureYamlFileType extends AbstractArchitectureYamlFileType {
	public static final ArchitectureYamlFileType INSTANCE = new ArchitectureYamlFileType()
	
	new() {
		super(ArchitectureYamlLanguage.INSTANCE)
	}
}
