version: '3'
services:
  example.users:
#    build: example.users/.
    image: gcr.io/example/example.users:0.0.1-SNAPSHOT
    container_name: example.users
    hostname: example.users
#working_dir: /
#command: java -Dorg.example.users.basePath=http://example.users:8091 -jar app.jar
    ports:
    - 8091:8091
    environment:
    - SPRING_CLOUD_CONFIG_URI="http://example.config:8888"
    - SPRING_CLOUD_CONFIG_LABEL="master"
    - SPRING_PROFILES_ACTIVE="local"
    - ORG_EXAMPLE_USERS_PORT_GRPC="7091"
    - ORG_EXAMPLE_USERS_PORT_REST="8091"
    - ORG_EXAMPLE_USERS_PORT_SOAP="9091"
    links:
    - example.config
    - example.mysql
#    - example.redis
    - example.elasticsearch
    networks:
    - example-network
  example.gateway:
    image: gcr.io/example/example.gateway:0.0.1-SNAPSHOT
    container_name: example.gateway
    hostname: example.gateway
    ports:
    - 8080:8080
    environment:
    - SPRING_CLOUD_CONFIG_URI="http://example.config:8888"
    - SPRING_CLOUD_CONFIG_LABEL="master"
    - SPRING_PROFILES_ACTIVE="local"
    - ORG_EXAMPLE_GATEWAY_PORT="8080"
    links:
    - example.config
    networks:
    - example-network
  example.oauth2:
    image: gcr.io/example/example.oauth2:0.0.1-SNAPSHOT
    container_name: example.oauth2
    hostname: example.oauth2
    ports:
    - 8081:8081
    environment:
    - SPRING_CLOUD_CONFIG_URI="http://example.config:8888"
    - SPRING_CLOUD_CONFIG_LABEL="master"
    - SPRING_PROFILES_ACTIVE="local"
    - ORG_EXAMPLE_OAUTH2_PORT="8081"
    links:
    - example.config
    networks:
    - example-network
  example.config:
    image: gcr.io/example/example.config:0.0.1-SNAPSHOT
    container_name: example.config
    hostname: example.config
    ports:
    - 8888:8888
    environment:
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI="https://tlaegler@bitbucket.org/tlaegler/microservice-config.git"
    - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME="test"
    - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD="test"
    - ORG_EXAMPLE_CONFIG_PORT="8888"
    networks:
    - example-network
  example.mysql:
    image: gcr.io/example/example.mysql:0.0.1-SNAPSHOT
    container_name: example.mysql
    hostname: example.mysql
    ports:
    - 3306:3306
    networks:
    - example-network
#  example.redis:
#    image: gcr.io/example/example.redis:0.0.1-SNAPSHOT
#    container_name: example.redis
#    hostname: example.redis
#    ports:
#    - 6379:6379
#    networks:
#    - example-network
  example.elasticsearch:
    image: gcr.io/example/example.elasticsearch:0.0.1-SNAPSHOT
    container_name: example.elasticsearch
    hostname: example.elasticsearch
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - cluster.name=example-cluster
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
    - esdata:/usr/share/elasticsearch/data
    networks:
    - example-network
volumes:
  esdata:
    driver: local
networks:
  example-network: null