/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.editor.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class ArchitectureLangIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new ArchitectureLangStandaloneSetupIdea().createInjector
	}

}
