/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel.impl;

import com.laegler.microservice.model.microserviceModel.GrpcJar;
import com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Grpc Jar</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.impl.GrpcJarImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.impl.GrpcJarImpl#getProtoInline <em>Proto Inline</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.impl.GrpcJarImpl#getProtoFile <em>Proto File</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GrpcJarImpl extends ArtifactImpl implements GrpcJar {
  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getProtoInline() <em>Proto Inline</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtoInline()
   * @generated
   * @ordered
   */
  protected static final String PROTO_INLINE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProtoInline() <em>Proto Inline</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtoInline()
   * @generated
   * @ordered
   */
  protected String protoInline = PROTO_INLINE_EDEFAULT;

  /**
   * The default value of the '{@link #getProtoFile() <em>Proto File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtoFile()
   * @generated
   * @ordered
   */
  protected static final String PROTO_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getProtoFile() <em>Proto File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProtoFile()
   * @generated
   * @ordered
   */
  protected String protoFile = PROTO_FILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GrpcJarImpl() {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass() {
    return MicroserviceModelPackage.Literals.GRPC_JAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDescription() {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescription(String newDescription) {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MicroserviceModelPackage.GRPC_JAR__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getProtoInline() {
    return protoInline;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProtoInline(String newProtoInline) {
    String oldProtoInline = protoInline;
    protoInline = newProtoInline;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MicroserviceModelPackage.GRPC_JAR__PROTO_INLINE, oldProtoInline, protoInline));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getProtoFile() {
    return protoFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProtoFile(String newProtoFile) {
    String oldProtoFile = protoFile;
    protoFile = newProtoFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MicroserviceModelPackage.GRPC_JAR__PROTO_FILE, oldProtoFile, protoFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType) {
    switch (featureID) {
      case MicroserviceModelPackage.GRPC_JAR__DESCRIPTION:
        return getDescription();
      case MicroserviceModelPackage.GRPC_JAR__PROTO_INLINE:
        return getProtoInline();
      case MicroserviceModelPackage.GRPC_JAR__PROTO_FILE:
        return getProtoFile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue) {
    switch (featureID) {
      case MicroserviceModelPackage.GRPC_JAR__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MicroserviceModelPackage.GRPC_JAR__PROTO_INLINE:
        setProtoInline((String)newValue);
        return;
      case MicroserviceModelPackage.GRPC_JAR__PROTO_FILE:
        setProtoFile((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID) {
    switch (featureID) {
      case MicroserviceModelPackage.GRPC_JAR__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MicroserviceModelPackage.GRPC_JAR__PROTO_INLINE:
        setProtoInline(PROTO_INLINE_EDEFAULT);
        return;
      case MicroserviceModelPackage.GRPC_JAR__PROTO_FILE:
        setProtoFile(PROTO_FILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID) {
    switch (featureID) {
      case MicroserviceModelPackage.GRPC_JAR__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MicroserviceModelPackage.GRPC_JAR__PROTO_INLINE:
        return PROTO_INLINE_EDEFAULT == null ? protoInline != null : !PROTO_INLINE_EDEFAULT.equals(protoInline);
      case MicroserviceModelPackage.GRPC_JAR__PROTO_FILE:
        return PROTO_FILE_EDEFAULT == null ? protoFile != null : !PROTO_FILE_EDEFAULT.equals(protoFile);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString() {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (description: ");
    result.append(description);
    result.append(", protoInline: ");
    result.append(protoInline);
    result.append(", protoFile: ");
    result.append(protoFile);
    result.append(')');
    return result.toString();
  }

} //GrpcJarImpl
