/**
 * generated by Xtext 2.12.0
 */
package microserviceModel;

import java.util.List;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Architecture</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link microserviceModel.Architecture#getArtifacts <em>Artifacts</em>}</li>
 * </ul>
 *
 * @see microserviceModel.MicroserviceModelPackage#getArchitecture()
 * @model
 * @generated
 */
public interface Architecture extends EObject {
	/**
	 * Returns the value of the '<em><b>Artifacts</b></em>' containment reference list.
	 * The list contents are of type {@link microserviceModel.Artifact}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Artifacts</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Artifacts</em>' containment reference list.
	 * @see microserviceModel.MicroserviceModelPackage#getArchitecture_Artifacts()
	 * @model containment="true"
	 * @generated
	 */
	List<Artifact> getArtifacts();

} // Architecture
