/**
 * generated by Xtext 2.12.0
 */
package microserviceModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grpc Expose</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link microserviceModel.GrpcExpose#getProtoInline <em>Proto Inline</em>}</li>
 *   <li>{@link microserviceModel.GrpcExpose#getProtoFile <em>Proto File</em>}</li>
 * </ul>
 *
 * @see microserviceModel.MicroserviceModelPackage#getGrpcExpose()
 * @model
 * @generated
 */
public interface GrpcExpose extends Expose {
	/**
	 * Returns the value of the '<em><b>Proto Inline</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Proto Inline</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Proto Inline</em>' attribute.
	 * @see #setProtoInline(String)
	 * @see microserviceModel.MicroserviceModelPackage#getGrpcExpose_ProtoInline()
	 * @model
	 * @generated
	 */
	String getProtoInline();

	/**
	 * Sets the value of the '{@link microserviceModel.GrpcExpose#getProtoInline <em>Proto Inline</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Proto Inline</em>' attribute.
	 * @see #getProtoInline()
	 * @generated
	 */
	void setProtoInline(String value);

	/**
	 * Returns the value of the '<em><b>Proto File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Proto File</em>' attribute isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Proto File</em>' attribute.
	 * @see #setProtoFile(String)
	 * @see microserviceModel.MicroserviceModelPackage#getGrpcExpose_ProtoFile()
	 * @model
	 * @generated
	 */
	String getProtoFile();

	/**
	 * Sets the value of the '{@link microserviceModel.GrpcExpose#getProtoFile <em>Proto File</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Proto File</em>' attribute.
	 * @see #getProtoFile()
	 * @generated
	 */
	void setProtoFile(String value);

} // GrpcExpose
