/**
 * generated by Xtext 2.12.0
 */
package microserviceModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see microserviceModel.MicroserviceModelFactory
 * @model kind="package"
 * @generated
 */
public interface MicroserviceModelPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "microserviceModel";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.laegler.com/microservice/model/MicroserviceModel";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "microserviceModel";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	MicroserviceModelPackage eINSTANCE = microserviceModel.impl.MicroserviceModelPackageImpl.init();

	/**
	 * The meta object id for the '{@link microserviceModel.impl.ArchitectureImpl <em>Architecture</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.ArchitectureImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getArchitecture()
	 * @generated
	 */
	int ARCHITECTURE = 0;

	/**
	 * The feature id for the '<em><b>Artifacts</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ARCHITECTURE__ARTIFACTS = 0;

	/**
	 * The number of structural features of the '<em>Architecture</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ARCHITECTURE_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.ArtifactImpl <em>Artifact</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.ArtifactImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getArtifact()
	 * @generated
	 */
	int ARTIFACT = 1;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ARTIFACT__NAME = 0;

	/**
	 * The number of structural features of the '<em>Artifact</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ARTIFACT_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.SpringImpl <em>Spring</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.SpringImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getSpring()
	 * @generated
	 */
	int SPRING = 2;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__NAME = ARTIFACT__NAME;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__TYPE = ARTIFACT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__DESCRIPTION = ARTIFACT_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Exposes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__EXPOSES = ARTIFACT_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Consumes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__CONSUMES = ARTIFACT_FEATURE_COUNT + 3;

	/**
	 * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__DEPENDENCIES = ARTIFACT_FEATURE_COUNT + 4;

	/**
	 * The feature id for the '<em><b>Model</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING__MODEL = ARTIFACT_FEATURE_COUNT + 5;

	/**
	 * The number of structural features of the '<em>Spring</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPRING_FEATURE_COUNT = ARTIFACT_FEATURE_COUNT + 6;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.GatewayImpl <em>Gateway</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.GatewayImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGateway()
	 * @generated
	 */
	int GATEWAY = 3;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GATEWAY__NAME = ARTIFACT__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GATEWAY__DESCRIPTION = ARTIFACT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Routes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GATEWAY__ROUTES = ARTIFACT_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Gateway</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GATEWAY_FEATURE_COUNT = ARTIFACT_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.RouteImpl <em>Route</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.RouteImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRoute()
	 * @generated
	 */
	int ROUTE = 4;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROUTE__NAME = 0;

	/**
	 * The feature id for the '<em><b>Urlmatcher</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROUTE__URLMATCHER = 1;

	/**
	 * The feature id for the '<em><b>Target Service</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROUTE__TARGET_SERVICE = 2;

	/**
	 * The number of structural features of the '<em>Route</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROUTE_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.GrpcJarImpl <em>Grpc Jar</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.GrpcJarImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcJar()
	 * @generated
	 */
	int GRPC_JAR = 5;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_JAR__NAME = ARTIFACT__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_JAR__DESCRIPTION = ARTIFACT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Proto Inline</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_JAR__PROTO_INLINE = ARTIFACT_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Proto File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_JAR__PROTO_FILE = ARTIFACT_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Grpc Jar</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_JAR_FEATURE_COUNT = ARTIFACT_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.JarImpl <em>Jar</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.JarImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getJar()
	 * @generated
	 */
	int JAR = 6;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JAR__NAME = ARTIFACT__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JAR__DESCRIPTION = ARTIFACT_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Jar</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JAR_FEATURE_COUNT = ARTIFACT_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.OptionImpl <em>Option</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.OptionImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getOption()
	 * @generated
	 */
	int OPTION = 7;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPTION__NAME = ARTIFACT__NAME;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPTION__VALUE = ARTIFACT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Flag</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPTION__FLAG = ARTIFACT_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Option</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int OPTION_FEATURE_COUNT = ARTIFACT_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.ExposeImpl <em>Expose</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.ExposeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getExpose()
	 * @generated
	 */
	int EXPOSE = 8;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPOSE__NAME = 0;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPOSE__DESCRIPTION = 1;

	/**
	 * The feature id for the '<em><b>Draft</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPOSE__DRAFT = 2;

	/**
	 * The feature id for the '<em><b>Port</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPOSE__PORT = 3;

	/**
	 * The number of structural features of the '<em>Expose</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPOSE_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.RestExposeImpl <em>Rest Expose</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.RestExposeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRestExpose()
	 * @generated
	 */
	int REST_EXPOSE = 9;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__NAME = EXPOSE__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__DESCRIPTION = EXPOSE__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Draft</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__DRAFT = EXPOSE__DRAFT;

	/**
	 * The feature id for the '<em><b>Port</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__PORT = EXPOSE__PORT;

	/**
	 * The feature id for the '<em><b>Endpoint</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__ENDPOINT = EXPOSE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Swagger File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE__SWAGGER_FILE = EXPOSE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Rest Expose</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_EXPOSE_FEATURE_COUNT = EXPOSE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.GrpcExposeImpl <em>Grpc Expose</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.GrpcExposeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcExpose()
	 * @generated
	 */
	int GRPC_EXPOSE = 10;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__NAME = EXPOSE__NAME;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__DESCRIPTION = EXPOSE__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Draft</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__DRAFT = EXPOSE__DRAFT;

	/**
	 * The feature id for the '<em><b>Port</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__PORT = EXPOSE__PORT;

	/**
	 * The feature id for the '<em><b>Proto Inline</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__PROTO_INLINE = EXPOSE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Proto File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE__PROTO_FILE = EXPOSE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Grpc Expose</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_EXPOSE_FEATURE_COUNT = EXPOSE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.ConsumeImpl <em>Consume</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.ConsumeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getConsume()
	 * @generated
	 */
	int CONSUME = 11;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONSUME__DESCRIPTION = 0;

	/**
	 * The number of structural features of the '<em>Consume</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONSUME_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.RestConsumeImpl <em>Rest Consume</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.RestConsumeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRestConsume()
	 * @generated
	 */
	int REST_CONSUME = 12;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_CONSUME__DESCRIPTION = CONSUME__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Target</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_CONSUME__TARGET = CONSUME_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Rest Consume</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REST_CONSUME_FEATURE_COUNT = CONSUME_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.GrpcConsumeImpl <em>Grpc Consume</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.GrpcConsumeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcConsume()
	 * @generated
	 */
	int GRPC_CONSUME = 13;

	/**
	 * The feature id for the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_CONSUME__DESCRIPTION = CONSUME__DESCRIPTION;

	/**
	 * The feature id for the '<em><b>Target</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_CONSUME__TARGET = CONSUME_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Grpc Consume</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GRPC_CONSUME_FEATURE_COUNT = CONSUME_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.DependencyImpl <em>Dependency</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.DependencyImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getDependency()
	 * @generated
	 */
	int DEPENDENCY = 14;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEPENDENCY__NAME = 0;

	/**
	 * The feature id for the '<em><b>Target</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEPENDENCY__TARGET = 1;

	/**
	 * The number of structural features of the '<em>Dependency</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEPENDENCY_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.EntityModelImpl <em>Entity Model</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.EntityModelImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEntityModel()
	 * @generated
	 */
	int ENTITY_MODEL = 15;

	/**
	 * The feature id for the '<em><b>Entities</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY_MODEL__ENTITIES = 0;

	/**
	 * The feature id for the '<em><b>Enumerations</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY_MODEL__ENUMERATIONS = 1;

	/**
	 * The feature id for the '<em><b>Relationships</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY_MODEL__RELATIONSHIPS = 2;

	/**
	 * The number of structural features of the '<em>Entity Model</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY_MODEL_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.EntityImpl <em>Entity</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.EntityImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEntity()
	 * @generated
	 */
	int ENTITY = 16;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY__NAME = 0;

	/**
	 * The feature id for the '<em><b>Label</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY__LABEL = 1;

	/**
	 * The feature id for the '<em><b>Documentation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY__DOCUMENTATION = 2;

	/**
	 * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY__ATTRIBUTES = 3;

	/**
	 * The number of structural features of the '<em>Entity</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENTITY_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.EnumerationImpl <em>Enumeration</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.EnumerationImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEnumeration()
	 * @generated
	 */
	int ENUMERATION = 17;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENUMERATION__NAME = 0;

	/**
	 * The feature id for the '<em><b>Label</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENUMERATION__LABEL = 1;

	/**
	 * The feature id for the '<em><b>Documentation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENUMERATION__DOCUMENTATION = 2;

	/**
	 * The feature id for the '<em><b>Enum Values</b></em>' attribute list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENUMERATION__ENUM_VALUES = 3;

	/**
	 * The number of structural features of the '<em>Enumeration</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ENUMERATION_FEATURE_COUNT = 4;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.AttributeImpl <em>Attribute</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.AttributeImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getAttribute()
	 * @generated
	 */
	int ATTRIBUTE = 18;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE__NAME = 0;

	/**
	 * The feature id for the '<em><b>Label</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE__LABEL = 1;

	/**
	 * The feature id for the '<em><b>Documentation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE__DOCUMENTATION = 2;

	/**
	 * The feature id for the '<em><b>Primary Key</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE__PRIMARY_KEY = 3;

	/**
	 * The feature id for the '<em><b>Type</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE__TYPE = 4;

	/**
	 * The number of structural features of the '<em>Attribute</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ATTRIBUTE_FEATURE_COUNT = 5;

	/**
	 * The meta object id for the '{@link microserviceModel.impl.RelationshipImpl <em>Relationship</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.impl.RelationshipImpl
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRelationship()
	 * @generated
	 */
	int RELATIONSHIP = 19;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP__NAME = 0;

	/**
	 * The feature id for the '<em><b>Label</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP__LABEL = 1;

	/**
	 * The feature id for the '<em><b>Documentation</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP__DOCUMENTATION = 2;

	/**
	 * The feature id for the '<em><b>From</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP__FROM = 3;

	/**
	 * The feature id for the '<em><b>To</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP__TO = 4;

	/**
	 * The number of structural features of the '<em>Relationship</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RELATIONSHIP_FEATURE_COUNT = 5;

	/**
	 * The meta object id for the '{@link microserviceModel.SpringType <em>Spring Type</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.SpringType
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getSpringType()
	 * @generated
	 */
	int SPRING_TYPE = 20;


	/**
	 * The meta object id for the '{@link microserviceModel.BaseTypeEnum <em>Base Type Enum</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see microserviceModel.BaseTypeEnum
	 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getBaseTypeEnum()
	 * @generated
	 */
	int BASE_TYPE_ENUM = 21;


	/**
	 * Returns the meta object for class '{@link microserviceModel.Architecture <em>Architecture</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Architecture</em>'.
	 * @see microserviceModel.Architecture
	 * @generated
	 */
	EClass getArchitecture();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Architecture#getArtifacts <em>Artifacts</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Artifacts</em>'.
	 * @see microserviceModel.Architecture#getArtifacts()
	 * @see #getArchitecture()
	 * @generated
	 */
	EReference getArchitecture_Artifacts();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Artifact <em>Artifact</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Artifact</em>'.
	 * @see microserviceModel.Artifact
	 * @generated
	 */
	EClass getArtifact();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Artifact#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Artifact#getName()
	 * @see #getArtifact()
	 * @generated
	 */
	EAttribute getArtifact_Name();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Spring <em>Spring</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Spring</em>'.
	 * @see microserviceModel.Spring
	 * @generated
	 */
	EClass getSpring();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Spring#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Type</em>'.
	 * @see microserviceModel.Spring#getType()
	 * @see #getSpring()
	 * @generated
	 */
	EAttribute getSpring_Type();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Spring#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.Spring#getDescription()
	 * @see #getSpring()
	 * @generated
	 */
	EAttribute getSpring_Description();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Spring#getExposes <em>Exposes</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Exposes</em>'.
	 * @see microserviceModel.Spring#getExposes()
	 * @see #getSpring()
	 * @generated
	 */
	EReference getSpring_Exposes();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Spring#getConsumes <em>Consumes</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Consumes</em>'.
	 * @see microserviceModel.Spring#getConsumes()
	 * @see #getSpring()
	 * @generated
	 */
	EReference getSpring_Consumes();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Spring#getDependencies <em>Dependencies</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Dependencies</em>'.
	 * @see microserviceModel.Spring#getDependencies()
	 * @see #getSpring()
	 * @generated
	 */
	EReference getSpring_Dependencies();

	/**
	 * Returns the meta object for the containment reference '{@link microserviceModel.Spring#getModel <em>Model</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Model</em>'.
	 * @see microserviceModel.Spring#getModel()
	 * @see #getSpring()
	 * @generated
	 */
	EReference getSpring_Model();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Gateway <em>Gateway</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Gateway</em>'.
	 * @see microserviceModel.Gateway
	 * @generated
	 */
	EClass getGateway();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Gateway#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.Gateway#getDescription()
	 * @see #getGateway()
	 * @generated
	 */
	EAttribute getGateway_Description();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Gateway#getRoutes <em>Routes</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Routes</em>'.
	 * @see microserviceModel.Gateway#getRoutes()
	 * @see #getGateway()
	 * @generated
	 */
	EReference getGateway_Routes();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Route <em>Route</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Route</em>'.
	 * @see microserviceModel.Route
	 * @generated
	 */
	EClass getRoute();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Route#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Route#getName()
	 * @see #getRoute()
	 * @generated
	 */
	EAttribute getRoute_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Route#getUrlmatcher <em>Urlmatcher</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Urlmatcher</em>'.
	 * @see microserviceModel.Route#getUrlmatcher()
	 * @see #getRoute()
	 * @generated
	 */
	EAttribute getRoute_Urlmatcher();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.Route#getTargetService <em>Target Service</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Target Service</em>'.
	 * @see microserviceModel.Route#getTargetService()
	 * @see #getRoute()
	 * @generated
	 */
	EReference getRoute_TargetService();

	/**
	 * Returns the meta object for class '{@link microserviceModel.GrpcJar <em>Grpc Jar</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Grpc Jar</em>'.
	 * @see microserviceModel.GrpcJar
	 * @generated
	 */
	EClass getGrpcJar();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.GrpcJar#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.GrpcJar#getDescription()
	 * @see #getGrpcJar()
	 * @generated
	 */
	EAttribute getGrpcJar_Description();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.GrpcJar#getProtoInline <em>Proto Inline</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Proto Inline</em>'.
	 * @see microserviceModel.GrpcJar#getProtoInline()
	 * @see #getGrpcJar()
	 * @generated
	 */
	EAttribute getGrpcJar_ProtoInline();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.GrpcJar#getProtoFile <em>Proto File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Proto File</em>'.
	 * @see microserviceModel.GrpcJar#getProtoFile()
	 * @see #getGrpcJar()
	 * @generated
	 */
	EAttribute getGrpcJar_ProtoFile();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Jar <em>Jar</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Jar</em>'.
	 * @see microserviceModel.Jar
	 * @generated
	 */
	EClass getJar();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Jar#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.Jar#getDescription()
	 * @see #getJar()
	 * @generated
	 */
	EAttribute getJar_Description();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Option <em>Option</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Option</em>'.
	 * @see microserviceModel.Option
	 * @generated
	 */
	EClass getOption();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Option#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see microserviceModel.Option#getValue()
	 * @see #getOption()
	 * @generated
	 */
	EAttribute getOption_Value();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Option#getFlag <em>Flag</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Flag</em>'.
	 * @see microserviceModel.Option#getFlag()
	 * @see #getOption()
	 * @generated
	 */
	EAttribute getOption_Flag();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Expose <em>Expose</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Expose</em>'.
	 * @see microserviceModel.Expose
	 * @generated
	 */
	EClass getExpose();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Expose#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Expose#getName()
	 * @see #getExpose()
	 * @generated
	 */
	EAttribute getExpose_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Expose#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.Expose#getDescription()
	 * @see #getExpose()
	 * @generated
	 */
	EAttribute getExpose_Description();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Expose#isDraft <em>Draft</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Draft</em>'.
	 * @see microserviceModel.Expose#isDraft()
	 * @see #getExpose()
	 * @generated
	 */
	EAttribute getExpose_Draft();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Expose#getPort <em>Port</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Port</em>'.
	 * @see microserviceModel.Expose#getPort()
	 * @see #getExpose()
	 * @generated
	 */
	EAttribute getExpose_Port();

	/**
	 * Returns the meta object for class '{@link microserviceModel.RestExpose <em>Rest Expose</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Rest Expose</em>'.
	 * @see microserviceModel.RestExpose
	 * @generated
	 */
	EClass getRestExpose();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.RestExpose#getEndpoint <em>Endpoint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Endpoint</em>'.
	 * @see microserviceModel.RestExpose#getEndpoint()
	 * @see #getRestExpose()
	 * @generated
	 */
	EAttribute getRestExpose_Endpoint();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.RestExpose#getSwaggerFile <em>Swagger File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Swagger File</em>'.
	 * @see microserviceModel.RestExpose#getSwaggerFile()
	 * @see #getRestExpose()
	 * @generated
	 */
	EAttribute getRestExpose_SwaggerFile();

	/**
	 * Returns the meta object for class '{@link microserviceModel.GrpcExpose <em>Grpc Expose</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Grpc Expose</em>'.
	 * @see microserviceModel.GrpcExpose
	 * @generated
	 */
	EClass getGrpcExpose();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.GrpcExpose#getProtoInline <em>Proto Inline</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Proto Inline</em>'.
	 * @see microserviceModel.GrpcExpose#getProtoInline()
	 * @see #getGrpcExpose()
	 * @generated
	 */
	EAttribute getGrpcExpose_ProtoInline();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.GrpcExpose#getProtoFile <em>Proto File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Proto File</em>'.
	 * @see microserviceModel.GrpcExpose#getProtoFile()
	 * @see #getGrpcExpose()
	 * @generated
	 */
	EAttribute getGrpcExpose_ProtoFile();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Consume <em>Consume</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Consume</em>'.
	 * @see microserviceModel.Consume
	 * @generated
	 */
	EClass getConsume();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Consume#getDescription <em>Description</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Description</em>'.
	 * @see microserviceModel.Consume#getDescription()
	 * @see #getConsume()
	 * @generated
	 */
	EAttribute getConsume_Description();

	/**
	 * Returns the meta object for class '{@link microserviceModel.RestConsume <em>Rest Consume</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Rest Consume</em>'.
	 * @see microserviceModel.RestConsume
	 * @generated
	 */
	EClass getRestConsume();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.RestConsume#getTarget <em>Target</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Target</em>'.
	 * @see microserviceModel.RestConsume#getTarget()
	 * @see #getRestConsume()
	 * @generated
	 */
	EReference getRestConsume_Target();

	/**
	 * Returns the meta object for class '{@link microserviceModel.GrpcConsume <em>Grpc Consume</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Grpc Consume</em>'.
	 * @see microserviceModel.GrpcConsume
	 * @generated
	 */
	EClass getGrpcConsume();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.GrpcConsume#getTarget <em>Target</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Target</em>'.
	 * @see microserviceModel.GrpcConsume#getTarget()
	 * @see #getGrpcConsume()
	 * @generated
	 */
	EReference getGrpcConsume_Target();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Dependency <em>Dependency</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Dependency</em>'.
	 * @see microserviceModel.Dependency
	 * @generated
	 */
	EClass getDependency();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Dependency#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Dependency#getName()
	 * @see #getDependency()
	 * @generated
	 */
	EAttribute getDependency_Name();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.Dependency#getTarget <em>Target</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Target</em>'.
	 * @see microserviceModel.Dependency#getTarget()
	 * @see #getDependency()
	 * @generated
	 */
	EReference getDependency_Target();

	/**
	 * Returns the meta object for class '{@link microserviceModel.EntityModel <em>Entity Model</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Entity Model</em>'.
	 * @see microserviceModel.EntityModel
	 * @generated
	 */
	EClass getEntityModel();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.EntityModel#getEntities <em>Entities</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Entities</em>'.
	 * @see microserviceModel.EntityModel#getEntities()
	 * @see #getEntityModel()
	 * @generated
	 */
	EReference getEntityModel_Entities();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.EntityModel#getEnumerations <em>Enumerations</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Enumerations</em>'.
	 * @see microserviceModel.EntityModel#getEnumerations()
	 * @see #getEntityModel()
	 * @generated
	 */
	EReference getEntityModel_Enumerations();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.EntityModel#getRelationships <em>Relationships</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Relationships</em>'.
	 * @see microserviceModel.EntityModel#getRelationships()
	 * @see #getEntityModel()
	 * @generated
	 */
	EReference getEntityModel_Relationships();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Entity <em>Entity</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Entity</em>'.
	 * @see microserviceModel.Entity
	 * @generated
	 */
	EClass getEntity();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Entity#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Entity#getName()
	 * @see #getEntity()
	 * @generated
	 */
	EAttribute getEntity_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Entity#getLabel <em>Label</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Label</em>'.
	 * @see microserviceModel.Entity#getLabel()
	 * @see #getEntity()
	 * @generated
	 */
	EAttribute getEntity_Label();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Entity#getDocumentation <em>Documentation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Documentation</em>'.
	 * @see microserviceModel.Entity#getDocumentation()
	 * @see #getEntity()
	 * @generated
	 */
	EAttribute getEntity_Documentation();

	/**
	 * Returns the meta object for the containment reference list '{@link microserviceModel.Entity#getAttributes <em>Attributes</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Attributes</em>'.
	 * @see microserviceModel.Entity#getAttributes()
	 * @see #getEntity()
	 * @generated
	 */
	EReference getEntity_Attributes();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Enumeration <em>Enumeration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Enumeration</em>'.
	 * @see microserviceModel.Enumeration
	 * @generated
	 */
	EClass getEnumeration();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Enumeration#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Enumeration#getName()
	 * @see #getEnumeration()
	 * @generated
	 */
	EAttribute getEnumeration_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Enumeration#getLabel <em>Label</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Label</em>'.
	 * @see microserviceModel.Enumeration#getLabel()
	 * @see #getEnumeration()
	 * @generated
	 */
	EAttribute getEnumeration_Label();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Enumeration#getDocumentation <em>Documentation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Documentation</em>'.
	 * @see microserviceModel.Enumeration#getDocumentation()
	 * @see #getEnumeration()
	 * @generated
	 */
	EAttribute getEnumeration_Documentation();

	/**
	 * Returns the meta object for the attribute list '{@link microserviceModel.Enumeration#getEnumValues <em>Enum Values</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Enum Values</em>'.
	 * @see microserviceModel.Enumeration#getEnumValues()
	 * @see #getEnumeration()
	 * @generated
	 */
	EAttribute getEnumeration_EnumValues();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Attribute <em>Attribute</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Attribute</em>'.
	 * @see microserviceModel.Attribute
	 * @generated
	 */
	EClass getAttribute();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Attribute#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Attribute#getName()
	 * @see #getAttribute()
	 * @generated
	 */
	EAttribute getAttribute_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Attribute#getLabel <em>Label</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Label</em>'.
	 * @see microserviceModel.Attribute#getLabel()
	 * @see #getAttribute()
	 * @generated
	 */
	EAttribute getAttribute_Label();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Attribute#getDocumentation <em>Documentation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Documentation</em>'.
	 * @see microserviceModel.Attribute#getDocumentation()
	 * @see #getAttribute()
	 * @generated
	 */
	EAttribute getAttribute_Documentation();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Attribute#isPrimaryKey <em>Primary Key</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Primary Key</em>'.
	 * @see microserviceModel.Attribute#isPrimaryKey()
	 * @see #getAttribute()
	 * @generated
	 */
	EAttribute getAttribute_PrimaryKey();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.Attribute#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Type</em>'.
	 * @see microserviceModel.Attribute#getType()
	 * @see #getAttribute()
	 * @generated
	 */
	EReference getAttribute_Type();

	/**
	 * Returns the meta object for class '{@link microserviceModel.Relationship <em>Relationship</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Relationship</em>'.
	 * @see microserviceModel.Relationship
	 * @generated
	 */
	EClass getRelationship();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Relationship#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see microserviceModel.Relationship#getName()
	 * @see #getRelationship()
	 * @generated
	 */
	EAttribute getRelationship_Name();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Relationship#getLabel <em>Label</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Label</em>'.
	 * @see microserviceModel.Relationship#getLabel()
	 * @see #getRelationship()
	 * @generated
	 */
	EAttribute getRelationship_Label();

	/**
	 * Returns the meta object for the attribute '{@link microserviceModel.Relationship#getDocumentation <em>Documentation</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Documentation</em>'.
	 * @see microserviceModel.Relationship#getDocumentation()
	 * @see #getRelationship()
	 * @generated
	 */
	EAttribute getRelationship_Documentation();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.Relationship#getFrom <em>From</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>From</em>'.
	 * @see microserviceModel.Relationship#getFrom()
	 * @see #getRelationship()
	 * @generated
	 */
	EReference getRelationship_From();

	/**
	 * Returns the meta object for the reference '{@link microserviceModel.Relationship#getTo <em>To</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>To</em>'.
	 * @see microserviceModel.Relationship#getTo()
	 * @see #getRelationship()
	 * @generated
	 */
	EReference getRelationship_To();

	/**
	 * Returns the meta object for enum '{@link microserviceModel.SpringType <em>Spring Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Spring Type</em>'.
	 * @see microserviceModel.SpringType
	 * @generated
	 */
	EEnum getSpringType();

	/**
	 * Returns the meta object for enum '{@link microserviceModel.BaseTypeEnum <em>Base Type Enum</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Base Type Enum</em>'.
	 * @see microserviceModel.BaseTypeEnum
	 * @generated
	 */
	EEnum getBaseTypeEnum();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	MicroserviceModelFactory getMicroserviceModelFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link microserviceModel.impl.ArchitectureImpl <em>Architecture</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.ArchitectureImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getArchitecture()
		 * @generated
		 */
		EClass ARCHITECTURE = eINSTANCE.getArchitecture();

		/**
		 * The meta object literal for the '<em><b>Artifacts</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ARCHITECTURE__ARTIFACTS = eINSTANCE.getArchitecture_Artifacts();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.ArtifactImpl <em>Artifact</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.ArtifactImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getArtifact()
		 * @generated
		 */
		EClass ARTIFACT = eINSTANCE.getArtifact();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ARTIFACT__NAME = eINSTANCE.getArtifact_Name();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.SpringImpl <em>Spring</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.SpringImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getSpring()
		 * @generated
		 */
		EClass SPRING = eINSTANCE.getSpring();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SPRING__TYPE = eINSTANCE.getSpring_Type();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute SPRING__DESCRIPTION = eINSTANCE.getSpring_Description();

		/**
		 * The meta object literal for the '<em><b>Exposes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SPRING__EXPOSES = eINSTANCE.getSpring_Exposes();

		/**
		 * The meta object literal for the '<em><b>Consumes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SPRING__CONSUMES = eINSTANCE.getSpring_Consumes();

		/**
		 * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SPRING__DEPENDENCIES = eINSTANCE.getSpring_Dependencies();

		/**
		 * The meta object literal for the '<em><b>Model</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SPRING__MODEL = eINSTANCE.getSpring_Model();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.GatewayImpl <em>Gateway</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.GatewayImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGateway()
		 * @generated
		 */
		EClass GATEWAY = eINSTANCE.getGateway();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GATEWAY__DESCRIPTION = eINSTANCE.getGateway_Description();

		/**
		 * The meta object literal for the '<em><b>Routes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GATEWAY__ROUTES = eINSTANCE.getGateway_Routes();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.RouteImpl <em>Route</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.RouteImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRoute()
		 * @generated
		 */
		EClass ROUTE = eINSTANCE.getRoute();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ROUTE__NAME = eINSTANCE.getRoute_Name();

		/**
		 * The meta object literal for the '<em><b>Urlmatcher</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ROUTE__URLMATCHER = eINSTANCE.getRoute_Urlmatcher();

		/**
		 * The meta object literal for the '<em><b>Target Service</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ROUTE__TARGET_SERVICE = eINSTANCE.getRoute_TargetService();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.GrpcJarImpl <em>Grpc Jar</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.GrpcJarImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcJar()
		 * @generated
		 */
		EClass GRPC_JAR = eINSTANCE.getGrpcJar();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GRPC_JAR__DESCRIPTION = eINSTANCE.getGrpcJar_Description();

		/**
		 * The meta object literal for the '<em><b>Proto Inline</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GRPC_JAR__PROTO_INLINE = eINSTANCE.getGrpcJar_ProtoInline();

		/**
		 * The meta object literal for the '<em><b>Proto File</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GRPC_JAR__PROTO_FILE = eINSTANCE.getGrpcJar_ProtoFile();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.JarImpl <em>Jar</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.JarImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getJar()
		 * @generated
		 */
		EClass JAR = eINSTANCE.getJar();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute JAR__DESCRIPTION = eINSTANCE.getJar_Description();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.OptionImpl <em>Option</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.OptionImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getOption()
		 * @generated
		 */
		EClass OPTION = eINSTANCE.getOption();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute OPTION__VALUE = eINSTANCE.getOption_Value();

		/**
		 * The meta object literal for the '<em><b>Flag</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute OPTION__FLAG = eINSTANCE.getOption_Flag();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.ExposeImpl <em>Expose</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.ExposeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getExpose()
		 * @generated
		 */
		EClass EXPOSE = eINSTANCE.getExpose();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXPOSE__NAME = eINSTANCE.getExpose_Name();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXPOSE__DESCRIPTION = eINSTANCE.getExpose_Description();

		/**
		 * The meta object literal for the '<em><b>Draft</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXPOSE__DRAFT = eINSTANCE.getExpose_Draft();

		/**
		 * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute EXPOSE__PORT = eINSTANCE.getExpose_Port();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.RestExposeImpl <em>Rest Expose</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.RestExposeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRestExpose()
		 * @generated
		 */
		EClass REST_EXPOSE = eINSTANCE.getRestExpose();

		/**
		 * The meta object literal for the '<em><b>Endpoint</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute REST_EXPOSE__ENDPOINT = eINSTANCE.getRestExpose_Endpoint();

		/**
		 * The meta object literal for the '<em><b>Swagger File</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute REST_EXPOSE__SWAGGER_FILE = eINSTANCE.getRestExpose_SwaggerFile();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.GrpcExposeImpl <em>Grpc Expose</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.GrpcExposeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcExpose()
		 * @generated
		 */
		EClass GRPC_EXPOSE = eINSTANCE.getGrpcExpose();

		/**
		 * The meta object literal for the '<em><b>Proto Inline</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GRPC_EXPOSE__PROTO_INLINE = eINSTANCE.getGrpcExpose_ProtoInline();

		/**
		 * The meta object literal for the '<em><b>Proto File</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute GRPC_EXPOSE__PROTO_FILE = eINSTANCE.getGrpcExpose_ProtoFile();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.ConsumeImpl <em>Consume</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.ConsumeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getConsume()
		 * @generated
		 */
		EClass CONSUME = eINSTANCE.getConsume();

		/**
		 * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute CONSUME__DESCRIPTION = eINSTANCE.getConsume_Description();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.RestConsumeImpl <em>Rest Consume</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.RestConsumeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRestConsume()
		 * @generated
		 */
		EClass REST_CONSUME = eINSTANCE.getRestConsume();

		/**
		 * The meta object literal for the '<em><b>Target</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference REST_CONSUME__TARGET = eINSTANCE.getRestConsume_Target();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.GrpcConsumeImpl <em>Grpc Consume</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.GrpcConsumeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getGrpcConsume()
		 * @generated
		 */
		EClass GRPC_CONSUME = eINSTANCE.getGrpcConsume();

		/**
		 * The meta object literal for the '<em><b>Target</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference GRPC_CONSUME__TARGET = eINSTANCE.getGrpcConsume_Target();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.DependencyImpl <em>Dependency</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.DependencyImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getDependency()
		 * @generated
		 */
		EClass DEPENDENCY = eINSTANCE.getDependency();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute DEPENDENCY__NAME = eINSTANCE.getDependency_Name();

		/**
		 * The meta object literal for the '<em><b>Target</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DEPENDENCY__TARGET = eINSTANCE.getDependency_Target();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.EntityModelImpl <em>Entity Model</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.EntityModelImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEntityModel()
		 * @generated
		 */
		EClass ENTITY_MODEL = eINSTANCE.getEntityModel();

		/**
		 * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ENTITY_MODEL__ENTITIES = eINSTANCE.getEntityModel_Entities();

		/**
		 * The meta object literal for the '<em><b>Enumerations</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ENTITY_MODEL__ENUMERATIONS = eINSTANCE.getEntityModel_Enumerations();

		/**
		 * The meta object literal for the '<em><b>Relationships</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ENTITY_MODEL__RELATIONSHIPS = eINSTANCE.getEntityModel_Relationships();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.EntityImpl <em>Entity</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.EntityImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEntity()
		 * @generated
		 */
		EClass ENTITY = eINSTANCE.getEntity();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

		/**
		 * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENTITY__LABEL = eINSTANCE.getEntity_Label();

		/**
		 * The meta object literal for the '<em><b>Documentation</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENTITY__DOCUMENTATION = eINSTANCE.getEntity_Documentation();

		/**
		 * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.EnumerationImpl <em>Enumeration</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.EnumerationImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getEnumeration()
		 * @generated
		 */
		EClass ENUMERATION = eINSTANCE.getEnumeration();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENUMERATION__NAME = eINSTANCE.getEnumeration_Name();

		/**
		 * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENUMERATION__LABEL = eINSTANCE.getEnumeration_Label();

		/**
		 * The meta object literal for the '<em><b>Documentation</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENUMERATION__DOCUMENTATION = eINSTANCE.getEnumeration_Documentation();

		/**
		 * The meta object literal for the '<em><b>Enum Values</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ENUMERATION__ENUM_VALUES = eINSTANCE.getEnumeration_EnumValues();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.AttributeImpl <em>Attribute</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.AttributeImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getAttribute()
		 * @generated
		 */
		EClass ATTRIBUTE = eINSTANCE.getAttribute();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

		/**
		 * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ATTRIBUTE__LABEL = eINSTANCE.getAttribute_Label();

		/**
		 * The meta object literal for the '<em><b>Documentation</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ATTRIBUTE__DOCUMENTATION = eINSTANCE.getAttribute_Documentation();

		/**
		 * The meta object literal for the '<em><b>Primary Key</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ATTRIBUTE__PRIMARY_KEY = eINSTANCE.getAttribute_PrimaryKey();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

		/**
		 * The meta object literal for the '{@link microserviceModel.impl.RelationshipImpl <em>Relationship</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.impl.RelationshipImpl
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getRelationship()
		 * @generated
		 */
		EClass RELATIONSHIP = eINSTANCE.getRelationship();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute RELATIONSHIP__NAME = eINSTANCE.getRelationship_Name();

		/**
		 * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute RELATIONSHIP__LABEL = eINSTANCE.getRelationship_Label();

		/**
		 * The meta object literal for the '<em><b>Documentation</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute RELATIONSHIP__DOCUMENTATION = eINSTANCE.getRelationship_Documentation();

		/**
		 * The meta object literal for the '<em><b>From</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference RELATIONSHIP__FROM = eINSTANCE.getRelationship_From();

		/**
		 * The meta object literal for the '<em><b>To</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference RELATIONSHIP__TO = eINSTANCE.getRelationship_To();

		/**
		 * The meta object literal for the '{@link microserviceModel.SpringType <em>Spring Type</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.SpringType
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getSpringType()
		 * @generated
		 */
		EEnum SPRING_TYPE = eINSTANCE.getSpringType();

		/**
		 * The meta object literal for the '{@link microserviceModel.BaseTypeEnum <em>Base Type Enum</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see microserviceModel.BaseTypeEnum
		 * @see microserviceModel.impl.MicroserviceModelPackageImpl#getBaseTypeEnum()
		 * @generated
		 */
		EEnum BASE_TYPE_ENUM = eINSTANCE.getBaseTypeEnum();

	}

} //MicroserviceModelPackage
