/**
 * generated by Xtext 2.12.0
 */
package microserviceModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rest Consume</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link microserviceModel.RestConsume#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see microserviceModel.MicroserviceModelPackage#getRestConsume()
 * @model
 * @generated
 */
public interface RestConsume extends Consume {
	/**
	 * Returns the value of the '<em><b>Target</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Target</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Target</em>' reference.
	 * @see #setTarget(RestExpose)
	 * @see microserviceModel.MicroserviceModelPackage#getRestConsume_Target()
	 * @model
	 * @generated
	 */
	RestExpose getTarget();

	/**
	 * Sets the value of the '{@link microserviceModel.RestConsume#getTarget <em>Target</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Target</em>' reference.
	 * @see #getTarget()
	 * @generated
	 */
	void setTarget(RestExpose value);

} // RestConsume
