---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: product
  namespace: example
  labels:
    name: example
    app: example
spec:
  replicas: 2
  selector:
    matchLabels:
      name: example
      app: example
  template:
    metadata:
      labels:
        name: example
        app: example
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
      - name: product
        image: product:
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
