/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ArchitectureLangWebModule extends AbstractArchitectureLangWebModule {
}
