spring:
  data:
    elasticsearch:
      cluster-name: example-es-cluster
      cluster-nodes: example-es:9300
      properties:
        host: example-es
        port: 9300
        http:
          enabled: true
        path:
          data: target/es/data
          logs: target/es/logs
  redis:
    host: example-redis
    port: 6379
example:
  version:  @project.version@
  description: @project.description@
  java:
    version: @java.version@
  elasticsearch:
    product:
      indexName: userindex
      indexType: UserSearch
server:
  port: ${example.user.rest.port}