apiVersion: v1
kind: Service
metadata:
  name: example.users
  namespace: example-network
  labels:
    project: example
    app: example.users
    group: org.example
    version: 0.0.1-SNAPSHOT
    provider: john.doe
spec:
  selector:
    app: example.users
  ports:
  - name: http
    port: 8091
  - name: grpc
    port: 7091
