apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example.users
  namespace: example-network
  labels:
    project: example
    app: example.users
    group: org.example
    version: 0.0.1-SNAPSHOT
    provider: john.doe
spec:
  template:
    spec:
      containers:
      - name: example.users
        image: gcr.io/example/example.users:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://example.config:8888
        - name: SPRING_CLOUD_CONFIG_LABEL
          value: master
        - name: SPRING_PROFILES_ACTIVE
          value: local
        - name: ORG_EXAMPLE_USERS_PORT_GRPC
          value: 7091
        - name: ORG_EXAMPLE_USERS_PORT_REST
          value: 8091
        - name: ORG_EXAMPLE_USERS_PORT_SOAP
          value: 9091
        ports:
        - name: grpc
          containerPort: 7091
        - name: rest
          containerPort: 8091
        - name: soap
          containerPort: 9091
      restartPolicy: Always
      terminationGracePeriodSeconds: 30