/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;

import java.util.List;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.EntityModel#getEntities <em>Entities</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.EntityModel#getEnumerations <em>Enumerations</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.EntityModel#getRelationships <em>Relationships</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getEntityModel()
 * @model
 * @generated
 */
public interface EntityModel extends EObject {
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getEntityModel_Entities()
   * @model containment="true"
   * @generated
   */
  List<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Enumerations</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Enumeration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumerations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumerations</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getEntityModel_Enumerations()
   * @model containment="true"
   * @generated
   */
  List<Enumeration> getEnumerations();

  /**
   * Returns the value of the '<em><b>Relationships</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Relationship}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationships</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getEntityModel_Relationships()
   * @model containment="true"
   * @generated
   */
  List<Relationship> getRelationships();

} // EntityModel
