/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Option#getValue <em>Value</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Option#getFlag <em>Flag</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getOption()
 * @model
 * @generated
 */
public interface Option extends Artifact {
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getOption_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Option#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Flag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Flag</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flag</em>' attribute.
   * @see #setFlag(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getOption_Flag()
   * @model
   * @generated
   */
  String getFlag();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Option#getFlag <em>Flag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flag</em>' attribute.
   * @see #getFlag()
   * @generated
   */
  void setFlag(String value);

} // Option
