/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Route</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Route#getName <em>Name</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Route#getUrlmatcher <em>Urlmatcher</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Route#getTargetService <em>Target Service</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getRoute()
 * @model
 * @generated
 */
public interface Route extends EObject {
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getRoute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Route#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Urlmatcher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Urlmatcher</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Urlmatcher</em>' attribute.
   * @see #setUrlmatcher(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getRoute_Urlmatcher()
   * @model
   * @generated
   */
  String getUrlmatcher();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Route#getUrlmatcher <em>Urlmatcher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Urlmatcher</em>' attribute.
   * @see #getUrlmatcher()
   * @generated
   */
  void setUrlmatcher(String value);

  /**
   * Returns the value of the '<em><b>Target Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Service</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Service</em>' reference.
   * @see #setTargetService(Spring)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getRoute_TargetService()
   * @model
   * @generated
   */
  Spring getTargetService();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Route#getTargetService <em>Target Service</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Service</em>' reference.
   * @see #getTargetService()
   * @generated
   */
  void setTargetService(Spring value);

} // Route
