/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;

import java.util.List;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Spring</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getType <em>Type</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getDescription <em>Description</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getExposes <em>Exposes</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getConsumes <em>Consumes</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Spring#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring()
 * @model
 * @generated
 */
public interface Spring extends Artifact {
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.laegler.microservice.model.microserviceModel.SpringType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see com.laegler.microservice.model.microserviceModel.SpringType
   * @see #setType(SpringType)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Type()
   * @model
   * @generated
   */
  SpringType getType();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Spring#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see com.laegler.microservice.model.microserviceModel.SpringType
   * @see #getType()
   * @generated
   */
  void setType(SpringType value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Spring#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Exposes</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Expose}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exposes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exposes</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Exposes()
   * @model containment="true"
   * @generated
   */
  List<Expose> getExposes();

  /**
   * Returns the value of the '<em><b>Consumes</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Consume}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Consumes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consumes</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Consumes()
   * @model containment="true"
   * @generated
   */
  List<Consume> getConsumes();

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Dependency}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dependencies</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Dependencies()
   * @model containment="true"
   * @generated
   */
  List<Dependency> getDependencies();

  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference.
   * @see #setModel(EntityModel)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getSpring_Model()
   * @model containment="true"
   * @generated
   */
  EntityModel getModel();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Spring#getModel <em>Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' containment reference.
   * @see #getModel()
   * @generated
   */
  void setModel(EntityModel value);

} // Spring
