/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expose</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Expose#getName <em>Name</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Expose#getDescription <em>Description</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Expose#isDraft <em>Draft</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Expose#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getExpose()
 * @model
 * @generated
 */
public interface Expose extends EObject {
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getExpose_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Expose#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getExpose_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Expose#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Draft</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Draft</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Draft</em>' attribute.
   * @see #setDraft(boolean)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getExpose_Draft()
   * @model
   * @generated
   */
  boolean isDraft();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Expose#isDraft <em>Draft</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Draft</em>' attribute.
   * @see #isDraft()
   * @generated
   */
  void setDraft(boolean value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see #setPort(int)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getExpose_Port()
   * @model
   * @generated
   */
  int getPort();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Expose#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see #getPort()
   * @generated
   */
  void setPort(int value);

} // Expose
