/**
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.model.microserviceModel;

import java.util.List;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gateway</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Gateway#getDescription <em>Description</em>}</li>
 *   <li>{@link com.laegler.microservice.model.microserviceModel.Gateway#getRoutes <em>Routes</em>}</li>
 * </ul>
 *
 * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getGateway()
 * @model
 * @generated
 */
public interface Gateway extends Artifact {
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getGateway_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.laegler.microservice.model.microserviceModel.Gateway#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Routes</b></em>' containment reference list.
   * The list contents are of type {@link com.laegler.microservice.model.microserviceModel.Route}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Routes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Routes</em>' containment reference list.
   * @see com.laegler.microservice.model.microserviceModel.MicroserviceModelPackage#getGateway_Routes()
   * @model containment="true"
   * @generated
   */
  List<Route> getRoutes();

} // Gateway
