/**
 * generated by Xtext 2.12.0
 */
package microserviceModel.tests;

import junit.textui.TestRunner;

import microserviceModel.GrpcJar;
import microserviceModel.MicroserviceModelFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Grpc Jar</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class GrpcJarTest extends ArtifactTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(GrpcJarTest.class);
	}

	/**
	 * Constructs a new Grpc Jar test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GrpcJarTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Grpc Jar test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected GrpcJar getFixture() {
		return (GrpcJar)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceModelFactory.eINSTANCE.createGrpcJar());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //GrpcJarTest
