/**
 * generated by Xtext 2.12.0
 */
package microserviceModel.tests;

import junit.textui.TestRunner;

import microserviceModel.GrpcConsume;
import microserviceModel.MicroserviceModelFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Grpc Consume</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class GrpcConsumeTest extends ConsumeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(GrpcConsumeTest.class);
	}

	/**
	 * Constructs a new Grpc Consume test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GrpcConsumeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Grpc Consume test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected GrpcConsume getFixture() {
		return (GrpcConsume)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceModelFactory.eINSTANCE.createGrpcConsume());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //GrpcConsumeTest
