/**
 * generated by Xtext 2.12.0
 */
package microserviceModel.tests;

import junit.textui.TestRunner;

import microserviceModel.MicroserviceModelFactory;
import microserviceModel.RestConsume;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Rest Consume</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class RestConsumeTest extends ConsumeTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(RestConsumeTest.class);
	}

	/**
	 * Constructs a new Rest Consume test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RestConsumeTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Rest Consume test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected RestConsume getFixture() {
		return (RestConsume)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceModelFactory.eINSTANCE.createRestConsume());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //RestConsumeTest
