/**
 * generated by Xtext 2.12.0
 */
package microserviceModel.tests;

import junit.textui.TestRunner;

import microserviceModel.MicroserviceModelFactory;
import microserviceModel.Spring;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Spring</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SpringTest extends ArtifactTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SpringTest.class);
	}

	/**
	 * Constructs a new Spring test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpringTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Spring test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Spring getFixture() {
		return (Spring)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(MicroserviceModelFactory.eINSTANCE.createSpring());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SpringTest
