/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.yaml.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ArchitectureYamlIdeaModule extends AbstractArchitectureYamlIdeaModule {
}
