/*
 * generated by Xtext 2.12.0
 */
package com.laegler.microservice.modeler.yaml.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class ArchitectureYamlIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new ArchitectureYamlStandaloneSetupIdea().createInjector
	}

}
