//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.23 at 10:14:24 AM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.laegler.com/microservice/example/code2model/user/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.laegler.microservice.example.code2model.user.soap;
