FROM sonarqube:6.5

LABEL image "gcr.io/example/example.sonarqube:0.0.1-SNAPSHOT"
LABEL description "example sonarqube image"
LABEL maintainer "John Doe <john.doe@example.org>"

ENTRYPOINT ["./bin/run.sh"]

EXPOSE 9000